/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kvgfxupcwfroypicasrm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2Z2Z4dXBjd2Zyb3lwaWNhc3JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMTIwOTIsImV4cCI6MjA3NDg4ODA5Mn0.qnEyC5-6skwU_L8I1o_Er-rQ7M9bOkrDsoOXXGhKEac"